name: Notify users based on issue labels

on:
  label:
    types: [created, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@master
